### ISSUE TITLE
cannot find apikey for project

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/shub#112]
I just pull recent master - looks totally great and I really enjoy all those cool new features.

There is one thing that doens't work for me though. When I try to deploy to some specific target I get either 

```
Error: Could not find API key for endpoint ad-hoc.
```

or 
```
Error: "realtime-test" is not a valid Scrapinghub project ID. Please check your scrapinghub.yml
```

am I missing something here or is it some potential bug?

EDIT:

I see this is changed behavior. Looking at line here: https://github.com/scrapinghub/shub/blob/master/shub/config.py#L134 I must have defined apikeys for all endpoints. In the past if I had default apikey it was used for all endpoints, is this change expected and intended?

**Comment by jdemaeyer** [comment]
Hey pawel, thanks alot for the feedback!

I haven't used ScrapyRT so far. What does deploying a project to it mean? From the docs it looks to me like you need to run it within an existing Scrapy project, and that there's no endpoint to overwrite the project. Did `shub` use to work with it?

> In the past if I had default apikey it was used for all endpoints

Ah, hadn't thought of that. Any objections to reverting to this behaviour? (/cc @pablohoffman @dangra @eliasdorneles @josericardo)

**Comment by pawelmhm** [comment]
Hey @jdemaeyer 

there are actually two issues here:

1) not using default apikey if you do shub deploy name_of_project
2) scrapyrt

1 is definitely more important IMO. If I have "default" apikey I would expect it to be "default" so that it is used when deploying to all projects I deploy too. Otherwise I will have to define and store same apikey for multiple projects which seems inconvenient for me.

2 is less important. We use shub as parasites so we can accommodate all changes no problem. I see error is probably because there is no actual integer "project_id":https://github.com/scrapinghub/shub/blob/master/shub/config.py#L91 we can probably add some "project_id" if it's needed if project_id must be integer. Are there any important reasons why project is is integer? 

> What does deploying a project to it mean? 

deploy is just POST with egg to some endpoint with Basic Auth header. It is not used in open source version it is only used in some internal SH projects (I know about 2 of them).

**Comment by jdemaeyer** [comment]
> 1 is definitely more important IMO. If I have "default" apikey I would expect it to be "default" so that it is used when deploying to all projects I deploy too. Otherwise I will have to define and store same apikey for multiple projects which seems inconvenient for me.

Ohh sorry, I just saw that your `scrapinghub.yml` is a little misconfigured. You don't need to define an API key per project, but per endpoint. And you don't have to specify the endpoint if it is the default one. I.e. it should look more like this:
```
~/s/brandview (master ⚡↩=) cat scrapinghub.yml 
endpoints:
  realtime-vagrant: http://192.168.2.101:9000/
  realtime: http://realtime.brandviewapis.com/
  realtime-test: http://realtime.brandviewapis.com:9020/
  realtime-local: http://localhost:9000/
version: GIT
projects:
  realtime-vagrant: realtime-vagrant/realtime-vagrant
  realtime: realtime/realtime
  default: 1886
  ad-hoc: 15033
  realtime-test: realtime-test/realtime-test
  arathy-temp: 16206
  realtime-local: realtime-local/realtime-local
  keywords: 16014
  prod-cont: 3784
  prod: 1887
  prod-lowes: 28855
  email: 15176
  uk-groceries: 17316
```

much neater, eh? :) the default API key will be used now for all projects that don't specify an extra endpoint
