### ISSUE TITLE
Document using multiple API keys

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#121]
It is possible to provide multiple API keys without having to touch the `endpoints` setting, e.g.
```
# scrapinghub.yml
projects:
  default: 123
  otheruser: someoneelse/123
apikeys:
  default: abc
  someoneelse: def
```

This won't see much use but nevertheless should be documented in the advanced section of the readme.
