### ISSUE TITLE
Issues pushing dependencies with requirements: file: requirements.txt

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/shub#212]
I get this error when running the pushed spider in dash:

```
  File "/tmp/unpacked-eggs/Jinja2.egg/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

after running `shub deploy dev`:

```
{"spiders": 11, "version": "e3c2373-staging", "status": "ok", "project": 96282}
Run your spiders at: https://app.scrapinghub.com/p/96282/
```

`scrapinghub.yml`

```
endpoints:
  default: http://dash.scrapinghub.com/api/
projects:
  prod: 53476
  dev: 96282
  staging: 71294
version: GIT
requirements:
  file: requirements.txt
```

`requirements.txt`

```
demjson
requests
six
jsonschema==2.5.1
slackclient==1.0.0
Jinja2==2.8
fuzzywuzzy==0.10.0
```

`pip freeze` within my virtual environment doesn't list MarkupSafe, but the system-level pip freeze does.  I'm only seeing this in our dev project though, not staging.
