### ISSUE TITLE
Normalize project representation in ShubConfig

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#265]
Currently, `conf.projects` can contain a mixture of integers and dictionaries. E.g., the configuration file

```
projects:
  default: 12345
  prod:
    id: 33333
    stack: scrapy:1.1
```

Would lead to 
```
In [2]: load_shub_config().projects
Out[2]: {'default': 12345, 'prod': {'id': 33333, 'stack': 'scrapy:1.1'}}
```

We should normalize all projects to dictionaries when loading configuration data. However, the syntactic sugar in `scrapinghub.yml` should remain.
