### ISSUE TITLE
Customizing also Dockerfile paths in scrapinghub.yml

### ISSUE THREAD

**Issue by starrify** [scrapinghub/shub#368]
Currently the `shub image build` or similar commands accepts an optional argument `-f/--file` for specifying Dockerfile files in custom paths (thanks to #302).

This is a proposal to further enhance this feature by allowing such customization in the `scrapinghub.yml` configuration file. Example:
```yaml
projects:
  foo:
    id: 1
    image: true
    stack: null
    dockerfile: ./Dockerfile-foo
  bar:
    id: 2
    image: true
    stack: null
    dockerfile: ./Dockerfile-bar
```
