### ISSUE TITLE
Python wheels support

### ISSUE THREAD

**Issue by proway2** [scrapinghub/shub#427]
Since eggs are deprecated https://setuptools.pypa.io/en/latest/deprecated/commands.html#bdist-egg-create-a-python-egg-for-the-project it makes sense to add support for wheels.

Proposed config file:

```yaml
stacks:
  default: "scrapy:2.8"

projects:
  dev:
    id: 123
    requirements:
      file: requirements.txt
      wheels:
        - ../path/to/some-0.1.0-py3-none-any.whl
        - other.whl
  prod: 456

requirements:
  file: requirements.txt
  wheels:
    - /absolute/path/to/some.whl
```
